@startuml
' car "1" *-- "many" wheel : contains, composition, owns
' garage o-- car : include, aggregation, has
' garage o-- tools: aggregation
' car ..> fuel: uses, dependency
' car --> road: order, direct association
' car <|-- audi: Extension, inheritance
' driver - car : association, drives >

ПланСчетов "1" -- "*" Счет

' оборос сумма операций по Дебет и Кредит
Счет -- Оборот
' Сальдо - Остаток на отчетный период
Счет -- Сальдо

Счет -- ДвойнаяЗапись
' корреспонденция счетов
ДвойнаяЗапись -- Дебет
ДвойнаяЗапись -- Кредит
' с суммой
ДвойнаяЗапись --- Проводка

Счет -- СчетСинтетический
СчетСинтетический "1" -- "*" СчетАналитический
СчетАналитический -- СубСчет
СчетСинтетический -- ОборотнаяВедомость
Счет -- Пассив
Счет -- Актив

Корректировка - Сторно

Баланс -- СтатьяБаланса
Баланс -- ХозОперация
Баланс -- ПервичныеДокументы
Баланс -- ВидБаланса
Баланс -- Источник

Инвентаризация -- Полная
Инвентаризация -- Частичная
@enduml