@startuml (id=abs)
' car "1" *-- "many" wheel : contains, composition, owns
' garage o-- car : include, aggregation, has
' garage o-- tools: aggregation
' car ..> fuel: uses, dependency
' car --> road: order, direct association
' car <|-- audi: Extension, inheritance
' driver - car : association, drives >

ЭлементарнаяОперация -- Регистр 
ЭлементарнаяОперация -- BEM
BEM -- СчетBEM
BEM -- Полупроводки
Регистр -- ТипРегистра

ФинСхемаОперации -- СостоянияЗайма
СостоянияЗайма -- Действия
Действия -- ТипПродукта
Действия -- ШаблонБизнесОперации
ШаблонБизнесОперации -- ЭлементШаблона
ЭлементШаблона -- Операция
ЭлементШаблона -- Формула
Формула -- Теги
Операция -- ОперацияПУ
ОперацияПУ -- ЭлементарнаяОперация

ФинСхемаОперации -- СхемыПериодичности
СхемыПериодичности -- ПериодическиеДействия
ПериодическиеДействия - УслугиКомиссии
@enduml
